#localhost
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.host=localhost
spring.datasource.port=3306
spring.datasource.databases=test
spring.datasource.username=root
spring.datasource.password=root123ABC
spring.datasource.tableList=test

#redis
spring.redis.password=

dev.user.name=test

dataAsset.server.url=http://192.168.0.25:9009
dataAsset.server.host=192.168.0.25
dataAsset.server.port=9009